name: pymc-extras-test
channels:
- conda-forge
dependencies:
- blackjax
- ipywidgets
- ipython
- pymc
- pytest-cov
- pytest
- dask
- xhistogram
- statsmodels
- numba
- nutpie
- pip
- scikit-learn
- pip:
  - better_optimize
  - -e .
