name: pymc-extras-test
channels:
- conda-forge
- defaults
dependencies:
- pip
- pytest-cov>=2.5
- pytest>=3.0
- dask
- xhistogram
- statsmodels
- numba<=0.60.0
- pymc>=5.20
- pip:
  - blackjax
  - scikit-learn
  - better_optimize
